apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: urumi-dashboard-ingress
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  {{ if .Values.ingress.tls }}
  tls:
    - hosts:
        - dashboard.{{ .Values.domainSuffix }}
      secretName: {{ .Values.ingress.secretName | default "urumi-tls" }}
  {{ end }}
  rules:
    - host: dashboard.{{ .Values.domainSuffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: urumi-platform
                port:
                  number: {{ .Values.service.port }}
