apiVersion: v1
kind: Service
metadata:
  name: urumi-platform
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: urumi-platform